services:
  frontend:
    build:
      context: "./web-crawler-frontend/"
    ports:
      - 80:80
    environment:
      SERVER_URL: http://backend:8080
    restart: always
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build:
      context: "./web-crawler-backend/"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/webcrawler
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=docker
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://backend:8080/api/websites || exit 1"
        ]
      timeout: 5s
      interval: 10s
      retries: 10

  database:
    image: postgres:16.2
    environment:
      POSTGRES_DB: webcrawler
      POSTGRES_USER: user
      POSTGRES_PASSWORD: docker
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./database/WebsiteRecords.sql:/docker-entrypoint-initdb.d/WebsiteRecords.sql
      - ./database/Tags.sql:/docker-entrypoint-initdb.d/Tags.sql
      - ./database/CrawlLinks.sql:/docker-entrypoint-initdb.d/CrawlLinks.sql
      - ./database/CrawlResults.sql:/docker-entrypoint-initdb.d/CrawlResults.sql
      - ./database/Executions.sql:/docker-entrypoint-initdb.d/Executions.sql
      - ./database/PeriodicityTimes.sql:/docker-entrypoint-initdb.d/PeriodicityTimes.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -h localhost -U user -d webcrawler" ]
      timeout: 5s
      interval: 10s
      retries: 10

