version: '3.8'
services:
  database:
    image: postgres:16.2
    environment:
      POSTGRES_DB: webcrawler
      POSTGRES_USER: user
      POSTGRES_PASSWORD: docker
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./database/WebsiteRecords.sql:/docker-entrypoint-initdb.d/WebsiteRecords.sql
      - ./database/Tags.sql:/docker-entrypoint-initdb.d/Tags.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -h localhost -U user -d webcrawler" ]
      timeout: 5s
      interval: 10s
      retries: 10